### PR TITLE
fix: #233

### PR DESCRIPTION
**Pull request by laishulu**

### CODE REVIEW

**Comment by hlissner** [comment]
Ah, I understand now why base4 is too difficult to read. My bad, I had forgotten about terminal users. In GUI Emacs I use fringe bitmaps, e.g.

image

In which case, cyan becomes too loud. It may be better to give `git-gutter:modified` a different color from `git-gutter-fr:modified`, instead of changing `vc-modified` overall. I'll look into that.

For the time being, could you undo that one change?

**Comment by laishulu** [comment]
@hlissner modified following your instruction

**Comment by laishulu** [comment]
please merge if no problem.

**Comment by laishulu** [comment]
please merge.......

**Comment by hlissner** [comment]
Sorry for taking so long, I was away on a trip. Thanks for the PR!

**Pull request merged**
