### PR TITLE
WIP: Add Acario themes

### PR DESCRIPTION
**Pull request by gagbo**
# WIP Status
- [ ] The palette (especially the light one) is not totally over
- [ ] 256-colors should probably only use `color-xxx` colors ? Unsure
- [ ] No idea if there is something to do regarding treemacs et al.
- [ ] Remove dependencies to the "central" `acario-doom-themes` package (only helper functions to switch between light and dark variants quickly and other settings)

# Themes
These themes are my personal themes, going in pair to switch easily between the 2 styles.

## Dark variant
The dark variant is a very dark blueish background with a pretty saturated palette for foreground colors.
The foreground palette is a little skewed towards blue as well

## Light variant
The light variant is light cold background with a pretty saturated palette as well for foreground colors.

# Specific highlights
I changed a lot of the magit faces, but I think I still need to work on those to finish the faces in hunks (apparently I forgot something)

### CODE REVIEW

**Comment by ema2159** [comment]
I'm never merging this. This theme will never see the light. I'll merge this theme just to delete it before the next MELPA update. I'll prevent this theme from being seen from any other human being's eyes.
.
.
.
@gagbo just kidding, will you upload a couple of screenshots? also, could you test it outside of doom? I'm getting a `reference to free variable ‘doom-serif-font’` error

**Comment by gagbo** [comment]
I'll do the screenshots soon-ish :)
The free variable `doom-serif-font` is something I should work on as well (probably using a `boundp`)

**Comment by gagbo** [comment]
Current versions look like this (elisp, Python, Rust and C++)

acario-dark-2019-08-14
acario-light-2019-08-14

**Comment by ema2159** [comment]
It looks awesome! I'm just not a fan of the modeline (It gives me anxiety jaja)

**Comment by gagbo** [comment]
Yeah I don't like it either, I need to find something else for the modeline (active, and inactive)

**Comment by ema2159** [comment]
I'd advise going for the classical lightened/darkened bg color for the modeline

**Comment by ema2159** [comment]
This seems pretty ready to merge. Is it @gagbo?

**Comment by gagbo** [comment]
Yeah I think it's pretty okay now, I won't have time to tweak it soon. Worst case PRs will come.

Quick screenshots with the more muted active modeline :

acario-dark-2019-10-11
acario-light-2019-10-11

**Comment by ema2159** [comment]
Perfect!

**Pull request merged**
