### PR TITLE
Add powerline configs for doom-one-light

### PR DESCRIPTION
**Pull request by ztlevi**
Just try to make it consistent for powerline 😀

### CODE REVIEW

**Comment by ema2159** [comment]
Could you explain why is this necessary? A couple before/after screenshots would help a lot.

**Comment by ztlevi** [comment]
I thought it was something legacy. Hlissner told me he would add some support in general rather just doom-one-light. But it's been a year and nobody worries about this anymore...

**Comment by ema2159** [comment]
I do care about this (I'm a collaborator :D). There's general theming for powerline in the doom-themes-base.el file:

``` elisp
;; power
    (powerline-active0   :inherit 'mode-line :background bg)
    (powerline-active1   :inherit 'mode-line :background (doom-lighten 'bg 0.025))
    (powerline-active2   :inherit 'mode-line :foreground base8 :background (doom-lighten 'bg 0.08))
    (powerline-inactive0 :inherit 'mode-line-inactive :background base2)
    (powerline-inactive1 :inherit 'mode-line-inactive :background (doom-lighten 'base2 0.02))
    (powerline-inactive2 :inherit 'mode-line-inactive :background (doom-lighten 'base2 0.04))
```
I'm not sure if that's what enough.

**Comment by ztlevi** [comment]
Oh, well. I would suggest you inject similar codes with `custom-set-faces!` in your own `.doom.d`. The function is well documented and you can also take a look at my examples [here](https://github.com/ztlevi/doom-config/blob/master/+ui.el#L31).

The thing is there is no powerline/spaceline option there for doom users. I've been using spaceline for a year or two. And doom-modeline looks even cleaner and more elegant to me and why not give it a try.

**Comment by ema2159** [comment]
Shall I close this PR then?

**Pull request closed without merging**
