### PR TITLE
Add Laserwave theme

### PR DESCRIPTION
**Pull request by hyakt**
New theme inspired by the vscode  [LaserWave Theme](https://github.com/Jaredk3nt/laserwave)

screenshot:
screenshot-laserwave

### CODE REVIEW

**Comment by ema2159** [comment]
Pretty gorgeous! Could you show me screenshots of magit and a Markdown file? Usually these are the ones that are a little bit hard to get right.

**Comment by hyakt** [comment]
@ema2159 
Thank you for your confirmation!

**magit**
screenshot-magit


**markdown**
screenshot-markdown

**Comment by ema2159** [comment]
Give me some time to test it and use it. Overall I think it's incredibly beautiful.

**Comment by hyakt** [comment]
OK! Thank you.

**Comment by ema2159** [comment]
I think you could make the `bg-alt` color a little bit darker (like the modeline's color). I don't know if you use `solaire-mode`, but it should present a little bit more contrast with the non editing buffers.

**Comment by hyakt** [comment]
@ema2159 
I fixied the `bg-alt` color. 
Could you check the theme again?

And I changed the markdown-mode color.

**scrennshot**  
markdown

**Comment by ema2159** [comment]
Cool! Don't forget to add the theme (and yourself) to the README and the comments of the main package file.

**Comment by ema2159** [comment]
> Cool! Don't forget to add the theme (and yourself) to the README and the comments of the main package file.

This is the only thing that's missing. Everything else is really good.

**Comment by hyakt** [comment]
@ema2159 
Sorry. I'm late.
I added the theme to the README and the comments of the main package file.

**Comment by ema2159** [comment]
@hyakt, I've been thinking on changing the modeline's color to the magenta color used on the main package. Is that ok?

**Comment by ema2159** [comment]
It looks like this:
image

**Comment by hyakt** [comment]
@ema2159 
Sure! LGTM
I think it is closer to the the original laserwave theme.

**Pull request merged**
