### PR TITLE
gruvbox magit main view colors

### PR DESCRIPTION
**Pull request by shroomist**
covers magit primary display scheme.
btw, how do I align multiple columns by `:`?

before:
Screenshot 2019-11-15 at 14 31 51

after:
Screenshot 2019-11-15 at 14 31 17

### CODE REVIEW

**Comment by dinkonin** [comment]
You can align with `C-u M-x align-regexp` then choose `\(\s-*\):, 1, 1, and y`

**Comment by shroomist** [comment]
@dinkonin for some reason that doesn't work for me in evil-doom

**Comment by ema2159** [comment]
Could you show a before/after screenshot? I'm not sure if it is completely necessary to set all those magit faces explicitly

**Comment by shroomist** [comment]
was getting rid of those magentas primarily.
removed extras of @ema2159 comment

**Comment by ema2159** [comment]
Well that looks pretty nice to me. I'll merge it in the evening. Thanks!

**Pull request merged**
