### PR TITLE
Feature/solarized dark

### PR DESCRIPTION
**Pull request by Emiller88**
Add solarized dark. Basic inverse of `solarized-light`

Fixed a few issues with highlighting.

### CODE REVIEW

**Comment by ar1a** [comment]
What it looks like so far. I think the modeline needs to be fixed, as well as M-x

**Comment by ar1a** [comment]
I'm still keen on debugging this, @hlissner can you hit me up on discord sometime when you're free? preferably when @Emiller88 is online too

**Comment by jmorag** [comment]
How is this going? I've been itching to use solarized dark with doom for a while now :)

**Comment by Emiller88** [comment]
@jmorag Feel free to use it and put your complaints here. It's mainly been a lack of testing that's held it back from making the finishing touches on it!

**Comment by bittopaz** [comment]
Really looking forward this dark solarized theme.

I would like to test this on my laptop, but I still very new to Emacs eco-system.

Is there any guide that can tell how to I can set this dark theme on my laptop, please?

**Comment by jmorag** [comment]
The easiest way would probably be to just go to the `Files changed` pane of this pull request, copy and paste the diff into a `doom-solarized-dark.el` file and load it.

**Comment by bittopaz** [comment]
@Emiller88 I'm trying this on my Mac, and the folder color in modeline, (and also the language color) looks terrible for me.

Can we make a change for the color, please?

**Comment by Emiller88** [comment]
@bittopaz sorry for the extremely late reply. What color did you have in mind? You can also make a PR to this with any changes you want to see.

**Comment by bittopaz** [comment]
@Emiller88 no worries, I'm not using this theme anymore.

**Pull request closed without merging**
