### PR TITLE
Add doom-blend-bg and doom-blend-fg functions

### PR DESCRIPTION
**Pull request by gagbo**
These functions allow to tweak colors along the background<->foreground
axis instead of the black<->white one.

### CODE REVIEW

**Comment by hlissner** [comment]
What do these two functions do that `(doom-blend COLOR 'bg ALPHA)` (or `(doom-blend 'bg COLOR ALPHA)`) can't?

Also, can't both of these functions be simplified to a call to `doom-blend`? e.g.

```elisp
;;;###autoload
(defun doom-blend-fg (color alpha &optional use-alt)
  "Blend a COLOR (a hexidecimal string) with the current theme's foreground by a coefficient ALPHA (a float between
0 and 1).
If USE-ALT is set to t, blend with the 'fg-alt' color instead of the 'fg' color."
  (doom-blend color
              (if use-alt (doom-color 'fg-alt) (doom-color 'fg))
              (- 1 alpha)))

;;;###autoload
(defun doom-blend-bg (color alpha &optional use-alt)
  "Blend a COLOR (a hexidecimal string) with the current theme's blackground by a coefficient ALPHA (a float between
0 and 1).
If USE-ALT is set to t, blend with the 'bg-alt' color instead of the 'bg' color."
  (doom-blend color
              (if use-alt (doom-color 'bg-alt) (doom-color 'bg))
              (- 1 alpha)))
```

**Comment by gagbo** [comment]
I didn't think about just using `doom-blend`, even while copy-pasting the code to make it work :(

I started thinking about this function because I saw in themes that colors were almost always tweaked with `doom-darken` and `doom-lighten`, and I thought the api would be clearer if it was "towards bg" or "towards fg". But that's not a necessary change for sure.

**Comment by hlissner** [comment]
> I started thinking about this function because I saw in themes that colors were almost always tweaked with doom-darken and doom-lighten, and I thought the api would be clearer if it was "towards bg" or "towards fg". But that's not a necessary change for sure.

Ah, good point. Perhaps instead of adding these two new functions, we could add a third argument to `doom-darken` and `doom-lighten`, to specify a base. Instead of `"#FFFFFF"` and `#000000`. Perhaps it would make sense to use `(doom-color 'fg)` and `(doom-color 'bg)` as a default, instead?

**Comment by gagbo** [comment]
That's another possibility yeah, I was just afraid that a bunch of themes would look different and that it would make people notice.

**Comment by gagbo** [comment]
Definitely not needed

**Pull request closed without merging**
