### PR TITLE
Add widget faces.

### PR DESCRIPTION
**Pull request by seagle0128**

### CODE REVIEW

**Comment by ema2159** [comment]
Hi Vincent! Would you post a screenshot with examples?

**Comment by seagle0128** [comment]
Sure. 

While pressing Restore button:
Screen Shot 2019-07-31 at 9 34 24 PM

**Comment by ema2159** [comment]
Thanks Mr. Zhang!

**Comment by ema2159** [comment]
BTW, what was that explosion of Issues and PRs? Today I woke up and had 43243 mails from you jajajaja

**Comment by seagle0128** [comment]
The default colors are original red and green which are not match doom themes.

**Comment by ema2159** [comment]
jajaja no, I'm talking about all the other issues an comments jaja, it's funny that you made them all a the same time

**Comment by seagle0128** [comment]
Aha, I am a multi-threading computer 😄

**Comment by ema2159** [comment]
JAJAJAJA that's true

**Pull request merged**
