### PR TITLE
Update colors to match official Nord theme

### PR DESCRIPTION
**Pull request by Linuus**
Some small updates to make doom-nord look closer to the official nord Emacs theme.

Ruby before
Screenshot 2020-05-13 at 22 57 56

Ruby after
Screenshot 2020-05-13 at 22 54 19

Ruby official theme
Screenshot 2020-05-13 at 22 55 34

Elisp before
Screenshot 2020-05-13 at 23 02 17

Elisp after
Screenshot 2020-05-13 at 23 02 25

Elisp official theme
Screenshot 2020-05-13 at 23 03 31

### CODE REVIEW

**Comment by hlissner** [comment]
Please provide before and after screenshots, and include what major modes you've tested in (it'd be helpful to test in as many major modes as possible).

**Comment by ema2159** [comment]
Nord is one of the most difficult themes to follow since it changes way too often.

**Comment by Linuus** [comment]
I will get back with some screenshots. 👍

Also, the differences that I fix here has been there for a long time. They are present in the screenshots here for instance:
https://github.com/hlissner/emacs-doom-themes/issues/370

**Comment by Linuus** [comment]
@hlissner Added some before/after screenshots.

**Comment by hlissner** [comment]
Major-mode-specific fixes are a problem, mostly because what faces a mode uses is (almost) arbitrary. One mode will use the keywords face for keywords, another will use it for operators. This may look great in ruby and elisp (and it does), but I'm concerned about how it affects python, javascript and C modes. I'll give them a try this weekend and get back to you.

**Comment by ema2159** [comment]
Yeah. Usually I tend to use either Python or JavaScript as a reference since they're the most popular languages now days, since it's practically impossible to match every single major mode. However, I think the best thing to do is to match the colors with the official Emacs Nord implementation.

**Comment by Linuus** [comment]
> Major-mode-specific fixes are a problem, mostly because what faces a mode uses is (almost) arbitrary. One mode will use the keywords face for keywords, another will use it for operators. This may look great in ruby and elisp (and it does), but I'm concerned about how it affects python, javascript and C modes. I'll give them a try this weekend and get back to you.

These are not really major mode specific fixes though? I'm just trying to align doom-nord with the official Emacs Nord theme. They use these colors for constants etc.

**Python**

Before
Screenshot 2020-05-14 at 09 37 47

After
Screenshot 2020-05-14 at 09 37 51

Official theme
Screenshot 2020-05-14 at 09 37 38

**Comment by Linuus** [comment]
Anything else I can do to help with the reviews?

**Comment by ema2159** [comment]
Time! haha. I've been a little bit busy this week.

**Comment by Linuus** [comment]
Ha! Well, let me know if I can help out 😊

**Comment by ema2159** [comment]
Hi Linus! Thanks! Merging this now.

**Pull request merged**
