### PR TITLE
tweak solarized light theme

### PR DESCRIPTION
**Pull request by gdkrmr**

### CODE REVIEW

**Comment by ema2159** [comment]
Hi! Could you post screenshots with your changes?

**Comment by gdkrmr** [comment]
Helm buffer before:
Screenshot_2020-01-22_08-58-53
Helm buffer after:
Screenshot_2020-01-22_08-59-24
company completion before:
Screenshot_2020-01-22_09-02-28
company completion after:
Screenshot_2020-01-22_09-03-06
Widget before:
Screenshot_2020-01-22_11-07-59
Widget after:
Screenshot_2020-01-22_11-08-39

**Comment by ema2159** [comment]
Excelent job.

**Comment by gdkrmr** [comment]
There is probably more to come...

**Comment by ema2159** [comment]
I don't use much light themes so I rely on the users to find bugs. Thanks for your help!

**Pull request merged**
