### PR TITLE
Add: horizon theme

### PR DESCRIPTION
**Pull request by karetsu**

### CODE REVIEW

**Comment by ema2159** [comment]
Perfect! You could also add `(ivy-minibuffer-match-face-2 :foreground yellow :weight 'bold)` in the Ivy config to make the matching look like in company.

**Comment by karetsu** [comment]
Added this option in bc0f7e4 @ema2159 :)

**Comment by ema2159** [comment]
@karetsu line numbers should be a little bit more visible!

**Comment by karetsu** [comment]
@ema2159 modified, the line numbers are now the same as the comment face. I also added solaire's header line face to make centaur tabs not have a white background +1

**Comment by ema2159** [comment]
I think this is ready to merge. I'll test it a little bit further!

**Comment by ema2159** [comment]
Good job!

**Pull request merged**
