### PR TITLE
Add New Xcode Theme

### PR DESCRIPTION
**Pull request by kadenbarlow**
Theme based off of Xcode's dark theme

## doom-xcode
doom-xcode

### CODE REVIEW

**Comment by ianpan870102** [comment]
Any update on this one? I'd love to use this XCode theme! :)

**Comment by kadenbarlow** [comment]
Ah, yeah totally forgot about this PR. I'll go through it this weekend and clean up the conflicts and make sure everything looks good on my side. Then as it goes through review, I can make any changes that come up.

**Comment by pkazmier** [comment]
Wow, lots of great looking themes hidden in these PRs! Looking forward to this one.

**Comment by kadenbarlow** [comment]
@ema2159 Just wondering what next steps are on getting this reviewed?

**Comment by ema2159** [comment]
@kadenbarlow I just need time! I've been moving to Europe for my master's and I've been incredibly busy.

**Comment by kadenbarlow** [comment]
@ema2159 Ah I'm sorry! No rush from me! I just wanted to make sure it hadn't fallen through the cracks. Sorry to bug!

**Comment by ema2159** [comment]
@kadenbarlow no worries man! I'll review it as soon as I fin some time 😄

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the late response. Thanks for the PR!

**Pull request merged**
