### PR TITLE
Add: all-the-icons-dired dir face

### PR DESCRIPTION
**Pull request by bricewge**
It add a face for directories in `all-the-icons-dired`.

### CODE REVIEW

**Comment by ema2159** [comment]
Hi! Just two things. 
- Could you change the fg for the doc color? (I'll give you the proper variable face soon, I'm currently from my phone). This is to keep consistency with the treemacs/neotree dir icon face
- Could you post screenshots of this and the other PRs?

**Comment by ema2159** [comment]
It is the `doc-comment` variable which you should be using

**Comment by bricewge** [comment]
2019-08-19T17:10:02+02:00
2019-08-19T17:13:29+02:00
 The color for `solarized-dark` feel off after having it set to `fg`.

**Comment by ema2159** [comment]
1. Thanks for this PR!
2. Thanks for keeping the commits format
3. Thanks for using my Solarized implementation 
4. Thank for using `centaur-tabs` :D!

**Comment by bricewge** [comment]
You're welcome, thank you a lot for your work the solarized theme I had lost hope in seeing it in this repo!

**Pull request merged**
