### PR TITLE
Add new theme: doom-1337

### PR DESCRIPTION
**Pull request by ccmywish**
This is a port of 1337 theme based on [microsoft/vscode-themes/1337](https://github.com/microsoft/vscode-themes/tree/master/1337)

The original 1337 theme in VSCode
Screenshot from 2020-12-07 11-16-35

The doom-1337 theme in Emacs
Screenshot from 2020-12-07 11-17-59

### CODE REVIEW

**Review by hlissner — CHANGES_REQUESTED** [review]
Sorry for the tremendously late reply, but could you add an entry for this in README.md?

**Comment by ccmywish** [comment]
> Sorry for the tremendously late reply, but could you add an entry for this in README.md?

Hi, I've added it to README

But I'm wondering why I can't use `[some description][some link] ` this markdown format to point to VSCode's 1337 theme repo, do you know the reason?

**Comment by hlissner** [comment]
> But I'm wondering why I can't use [some description][some link] this markdown format to point to VSCode's 1337 theme repo, do you know the reason?

I think what you wanted was `[description](link)`. In order for `[description][short-link]` to work you need to dedclare `[short-link]` elsewhere in the file as I did in d51beeb.

-----

Anyhow, thanks for your submission!

**Comment by ccmywish** [comment]
Thank you for your information ~

**Pull request merged**
