### PR TITLE
New theme doom-solarized-dark-high-contrast

### PR DESCRIPTION
**Pull request by jmorag**
New theme, doom-solarized-dark-high-contrast, based on existing doom-solarized-dark and solarized-dark-high-contrast-theme from https://github.com/bbatsov/solarized-emacs.

Screenshots:
image
image
image

Let me know if you'd like any more!

### CODE REVIEW

**Review by hlissner — APPROVED** [review]

**Review by hlissner — CHANGES_REQUESTED** [review]
Please add an entry for the theme in the README.

**Comment by jmorag** [comment]
Done! Sorry for the big table diff. `doom-solarized-dark-high-contrast` is an unfortunately long name.

**Comment by jmorag** [comment]
Fixed the new merge conflicts.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
LGTM. Thanks for the submission!

**Pull request merged**
