### PR TITLE
Gruvbox: Remove background from org ellipses 

### PR DESCRIPTION
**Pull request by teesloane**
**Before**

Screenshot 2019-10-08 14 21 04

**After**
Screenshot 2019-10-08 14 21 18

### CODE REVIEW

**Comment by ema2159** [comment]
Hi! isn't it better to simply remove the background property?

**Comment by teesloane** [comment]
Hello! Just tried that and it worked too — would you prefer that instead?

**Comment by ema2159** [comment]
Yes!

**Comment by teesloane** [comment]
Done!

**Pull request merged**
