### PR TITLE
Add a shades-of-purple theme

### PR DESCRIPTION
**Pull request by jwbaldwin**
This is a theme off of one of the most popular VSCode extensions: Shades of Purple

Using their exact color scheme I tried to make it as pleasing as possible. Would love to see this added as it's one of the top themes for VSCode.

### CODE REVIEW

**Comment by pkazmier** [comment]
Looking forward to this new theme!

**Comment by ema2159** [comment]
Could you please post a screenshot here in the thread with several modes?

**Comment by jwbaldwin** [comment]
> Could you please post a screenshot here in the thread with several modes?

Will post as soon as I'm back online! Away for the weekend.

**Comment by ema2159** [comment]
I was about to try it but there's some syntax error that prevents it from loading!

**Comment by pkazmier** [comment]
I wanted to try as well, but got a bytecode overflow error.

**Comment by jwbaldwin** [comment]
@ema2159 @pkazmier Ah sorry, got busy and it slipped my mind. Fixed the syntax issue, not sure where the bytecode overflow error is coming from as I can't replicate.

Here's a screenshot from an old React repo I had laying around: 

Screen Shot 2020-10-21 at 12 21 05 PM

**Comment by ema2159** [comment]
It still throws an error. I really want to test this theme but I'm unable to!

**Comment by jwbaldwin** [comment]
@ema2159 No clue why I don't get those errors 🤦  

Just some hex codes. *Now* they should be fixed? 🤞

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the late response. Thanks for the submission!

**Pull request merged**
