### PR TITLE
doom-nova: clean up codes

### PR DESCRIPTION
**Pull request by dalugm**
- fix `Wrong type argument: listp, "#DF8C8C"`
- Besides, shall we keep `dark-grey` and `light-grey`? This theme doesn't use these two colors at all.

### CODE REVIEW

**Review by hlissner — APPROVED** [review]

**Review by hlissner — CHANGES_REQUESTED** [review]
> Besides, shall we keep dark-grey and light-grey? This theme doesn't use these two colors at all.

Ah, you're correct. In that case, could you remove them?

**Comment by dalugm** [comment]
> could you remove them?

Of course, I hope I didn't do it wrong 😄

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Looks good to me. Thanks for your help!

**Comment by dalugm** [comment]
Sorry, I forgot to trim the whitespace on Line 33. Can you remove it when you update this package next time? 😢

https://github.com/hlissner/emacs-doom-themes/blob/0f32ce9320d1108eae7084b54d8a381c7939ea02/themes/doom-nova-theme.el#L32-L34

---

I'm happy I can contribute to this awesome theme package, thanks for your working!

**Comment by hlissner** [comment]
No problem. Will do!

**Pull request merged**
