### PR TITLE
Adding my port of Franbach's miramare theme

### PR DESCRIPTION
**Pull request by sagittaros**
Hi! This is my first PR here and I made a variant based on [doom-gruvbox](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-gruvbox-theme.el).

[Miramare](https://github.com/franbach/miramare) is a vim theme by @franbach and I think it is a refreshing variant of the good-old gruvbox theme.

miramare

Because there are more colors in doom-themes than miramare, I have used some analogous color tones to fill the missing colors.

Opinions are welcomed!

### CODE REVIEW

**Comment by sagittaros** [comment]
Some screenshots

### Dired
dired

### Magit
magit

### Python and markdown
python-markdown

### Shell
shell

### Org
org

**Comment by ema2159** [comment]
Quite nice and earthy! I like it. I{ll give it a try soon.

**Comment by sagittaros** [comment]
Fixed syntax highlighting for React JSX. Screenshot here:

Screenshot 2020-08-04 at 10 59 29 PM

**Comment by ema2159** [comment]
Very good job man. So far so good, you've really polished this theme as much as you could. I'll test it a little bit more but I think it can be merged soon.

**Comment by ema2159** [comment]
I think one thing that can be improved is `ivy-minibuffer-match-face-2` face to give it a little bit more of contrast, since the yellow color looks too dim. Maybe a red-ish color would do the job.

**Comment by sagittaros** [comment]
Hi @ema2159 , this is a good suggestion, I was so used to it that I didn't notice it was hard to see.

This is before:
before

This is after:
after

And for the sake of completeness:
ivy

I will push my commits if you think they are okay. Thanks!

**Comment by ema2159** [comment]
That's perfect!

**Comment by ema2159** [comment]
@sagittaros friendly ping. Please update the faces!

**Comment by sagittaros** [comment]
@ema2159 sorry! pushed

**Comment by ema2159** [comment]
Done! Thank you very much for your work and time!

**Pull request merged**
