### PR TITLE
Add doom-light-theme

### PR DESCRIPTION
**Pull request by ztlevi**
I added the doom-light-theme cuz I am waiting for the light version for months...
Tried to polish the theme. 
Modified on lazy-highlight, evil-snipe, helm, show-paren-match, ivy, company, neotree, yasnippet, solaire-mode, css-mode, markdown-mode, org-mode.

### CODE REVIEW

**Comment by hlissner** [comment]
Thanks for this! Sorry to have kept you waiting. As usual, life gets in the way!

In any case, I'll have a look at this over the weekend!

**Comment by ztlevi** [comment]
It's OK. I just keep using and keep tweaking. 😂

**Comment by jwintz** [comment]
@ztlevi Really look forward trying it. Does it honor `salaire-mode` and `spaceline` ?

**Comment by ztlevi** [comment]
It does. Once I changed the base0-8 color, no need for directly editing to support those.

**Pull request merged**
