### PR TITLE
feature/doom-palenight

### PR DESCRIPTION
**Pull request by Brettm12345**
New theme inspired by the [vscode material palenight theme](https://github.com/whizkydee/vscode-material-palenight-themel)

img-2018-11-09-043341

### CODE REVIEW

**Comment by above-c-level** [comment]
Yes please

**Comment by ema2159** [comment]
Hi @Brettm12345, I'm implementing a new multi-themes package using Doom themes core. Can I use your implementation of the Moonlight and Palenight themes? I'll give you full credit

**Comment by Brettm12345** [comment]
> Hi @Brettm12345, I'm implementing a new multi-themes package using Doom themes core. Can I use your implementation of the Moonlight and Palenight themes? I'll give you full credit

Of course. Go ahead

**Comment by ema2159** [comment]
@Brettm12345 not anymore, now I'm a collaborator here so I'll be able to merge it here!

**Comment by ema2159** [comment]
Given that there's a lot of conflicts, I just grabbed the themes (just grabbed Palenight for now but soon I'll add Moonlight) and committed them co-authoring the commit with you. Hope that's ok. Palenight looks exquisite by the way, good job.

**Pull request closed without merging**
