### PR TITLE
Add missing filters; normalize colors

### PR DESCRIPTION
**Pull request by minikN**
Hello,

I've added the missing filters:
- Octagon
- Ristretto
- Machine
- Classic (Although there already is a classic variant, this one is slightly different. It's Hazenbergs own variant I guess
- Pro (I've converted the pro theme to match the other filters. The colors where not quite correct and it will benefit from the configuration I've already done)

I've also normalized colors throughout the filters. Unfortunately the original Palette doesn't provide all colors we need for the doom theme so I need to arbitrarily pick colors in between. I've gone over my previous PR again and unified what colors I pick for each filter so they don't appear random.
To put it simple: Every color for every filter I needed to add now has the same "distance" from the colors provided by the original palette itself making the filters look more uniform.
- Pro
image

- Pro (Classic)
image

- Spectrum
image

- Ristretto
image

- Machine
image

- Octagon
image

### CODE REVIEW

**Comment by minikN** [comment]
Sorry for the commits. Was a mistake. I resetted back to where it should be.

**Comment by ianpan870102** [comment]
Great effort man! Looking forward to seeing this be merged.

I created PR https://github.com/hlissner/emacs-doom-themes/pull/589 before I saw this PR. I have now closed mine in favor of yours. Feel free to compare the code and see if my port could be of any help :-)

**Comment by ema2159** [comment]
Just one thing that I hadn't mentioned, don't forget the docs! Both in the README and in doom-themes.el file!

**Comment by ema2159** [comment]
@minikN Could you take monokai-pro and classic out and submit them in a separate PR? This way we avoid conflicts and I can review more  in detail the changes introduced.

**Comment by hlissner** [comment]
@minikN Bump. Would you mind rebasing this onto master, and separating the doom-monokai-pro changes to another PR?

**Comment by minikN** [comment]
Sorry, I'm pretty occupied these days. Will do ASAP.

**Comment by minikN** [comment]
Don't know why/how I messed things up. I'll open a new one.

**Comment by minikN** [comment]
#601 #602

**Pull request closed without merging**
