### PR TITLE
be consistent with other themes' org-level faces

### PR DESCRIPTION
**Pull request by ztlevi**
A quick fix for org-level faces and web-mode element highlight.

### CODE REVIEW

**Comment by hlissner** [comment]
Ah, this PR slipped under my radar. Could you change `:bold` to `:weight`?

**Comment by ztlevi** [comment]
Ay, captain. I just did. My font only has the medium type. I didn't even notice it's not working before.

**Comment by hlissner** [comment]
Did you push them? I don't see the change in the pull request.

**Comment by ztlevi** [comment]
I rebased the commit instead of pushing another one.

**Comment by hlissner** [comment]
Oh, so you did! Excellent, thanks for your help!

**Pull request merged**
