### PR TITLE
Add: Solarized dark theme

### LINKED ISSUE #290: Solarized dark theme
Would you be open to implement the Solarized dark theme (or accept a PR)?

### PR DESCRIPTION
**Pull request by ema2159**
There's a Solarized light theme so there must be a Solarized dark! I Carefully chose all the faces according to the official theme page and also based some faces in VS Code's Solarized. Here is a sample on multiple modes. A sample of the general interface can be seen right here #290. Tell me what do you think mr. @hlissner. (fixes #290)
Elisp:
el
Markdown:
md
C:
c
Python:
py
Org:
org
Javascript:
js
HTML:
html

### CODE REVIEW

**Comment by ianpan870102** [comment]
Brilliant! Solarized Dark is indeed amongst the top themes! It'll be nice to have it on board.

One minor issue, I see you put `doom-solarized-dark-theme.el` at the project root level. But according to the repo structure, the individual theme files should go under the `themes` folder.

**Comment by ema2159** [comment]
> Brilliant! Solarized Dark is indeed amongst the top themes! It'll be nice to have it on board.
> 
> One minor issue, I see you put `doom-solarized-dark-theme.el` at the project root level. But according to the repo structure, the individual theme files should go under the `themes` folder.

You're right. Also, I should modify the README.

**Comment by ema2159** [comment]
Done, now it just needs to be reviewed by Mr. Lissner

**Comment by hlissner** [comment]
This looks good to me. In light of recent discussion, do you mind me merging this now?

**Comment by ema2159** [comment]
@hlissner if you're alright with the org faces (concretely the code blocks) you can merge it! ( What I did locally was to remove the background of the level 1 blocks and use that background for the whole code block.

**Comment by hlissner** [comment]
Great work! Good call on the org block faces; I would've suggested the same. Thanks for the PR!

**Comment by ema2159** [comment]
Your welcome! I'll help you as much as I can!

**Pull request merged**
