### PR TITLE
fix line-number-current-line for peacock 

### PR DESCRIPTION
**Pull request by ichirika**

### CODE REVIEW

**Comment by hlissner** [comment]
Ah, I'm sorry I wasn't clearer. I meant remove `linum-relative-current-face` completely and add `:underline nil` to both `line-number` and `line-number-current-line`. i.e.

```diff
-   (line-number :inherit 'default :foreground base4 :distant-foreground nil :bold nil)
-   (line-number-current-line :inherit 'hl-line :foreground base7 :distant-foreground nil :bold nil)
-   (linum-relative-current-face :underline nil)
+   (line-number :inherit 'default :foreground base4 :distant-foreground nil :bold nil :underline nil)
+   (line-number-current-line :inherit 'hl-line :foreground base7 :distant-foreground nil :bold nil :underline nil)
```

**Comment by ichirika** [comment]
Emmm..No... I just do as you said ,in second change, maybe u just saw the first one

**Comment by ichirika** [comment]
here is the second change
-   (line-number-current-line :inherit 'hl-line :foreground base7 :distant-foreground nil :bold nil)
+   (line-number-current-line :inherit 'hl-line :foreground base7 :distant-foreground nil :bold nil :underline nil)

**Comment by hlissner** [comment]
Yes, but that is only one of three changes I'm asking for:

+ [ ] Add `:underline nil` to `line-numbers`
+ [X] Add `:underline nil` to `line-number-current-line`
+ [ ] Remove `(linum-relative-current-face :underline nil)`

**Comment by ichirika** [comment]
emmm...lol... sorry im too careless,  try again later~ :D

**Pull request closed without merging**
