### PR TITLE
doom-one-light: Theme `selectrum-current-candidate'

### PR DESCRIPTION
**Pull request by leungbk**
----

#

### CODE REVIEW

**Comment by hlissner** [comment]
Please include before and after screenshots of your changes.

Also, in the future, please include links to packages that you are adding support for. e.g. [selectrum](https://github.com/raxod502/selectrum) and [marginalia](https://github.com/minad/marginalia).

**Comment by leungbk** [comment]
Sorry about that @hlissner.

Before theming `selectrum-current-candidate` and `marginalia`:

2020-12-11-164442_1920x1080_scrot

After theming `selectrum-current-candidate`, buf before theming `marginalia`:

2020-12-11-164619_1920x1080_scrot

After theming `selectrum-current-candidate` and `marginalia-variable`:

2020-12-11-165125_1920x1080_scrot

After theming `selectrum-current-candidate` and `marginalia-key`:

2020-12-11-165147_1920x1080_scrot

**Comment by leungbk** [comment]
Friendly ping @hlissner.

**Comment by ema2159** [comment]
Sorry for the delay!

**Pull request merged**
