### PR TITLE
Gruvbox Theme

### PR DESCRIPTION
**Pull request by JongW**
Hi! I'm new to writing lisp/elisp, but I've had a go at porting over the gruvbox theme to doom.

Any feedback would be greatly appreciated :smiley: 

---

**Screenshots**

gruvbox1
gruvbox2

### CODE REVIEW

**Comment by ema2159** [comment]
Hi @JongW! I'm currently implementing a new multi-theme package using the same core as Doom Themes but implementing a different set of themes. Can I use this PR in my package? I'll give you full credit for it.

**Comment by JongW** [comment]
@ema2159 Sure! Please do go ahead.

**Comment by ema2159** [comment]
Thanks!!! I hope to upload it to MELPA soon. Please stay tuned in my GitHub (the package is called `muse-themes`) or in Reddit, and  if you want to contribute porting more themes go ahead! I'll be happy to review them and include them!

**Comment by ema2159** [comment]
Now I'm a contributor here so I'll add your theme here 😁 I'll just do some minor changes

**Pull request merged**
